language: python

cache:
  pip: true
  directories:
    - webapp/frontend/node_modules

python:
 - "2.7"

addons:
  ssh_known_hosts: localhost

sudo: false

services: postgresql

before_install:
 - export DJANGO_SETTINGS_MODULE=webapp.settings
 - nvm install 0.12
 - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
 - "npm config set spin false"
 - "npm install -g npm@^2"

install: 
 - pip install tox ansible flake8-diff
 - cd webapp/frontend/
 - npm install -g bower
 - npm install
 - bower install
 - cd ../../

before_script:
 - psql -c "CREATE DATABASE lambda_db;" -U postgres
 - psql -c "CREATE USER lambda WITH PASSWORD 'change_me';" -U postgres
 - psql -c "ALTER USER lambda WITH SUPERUSER;" -U postgres

script:
 - git fetch origin $TRAVIS_BRANCH:travis_pr_branch
 - flake8-diff travis_pr_branch

 - cd core
 - python setup.py install
 - pip install -r requirements.txt
 - tox -e $TOXENV_CORE


 - cd ..
 - pip install -r devel_requirements.txt

 - cd webapp
 - python render_django_settings.py

 - pip install -r requirements.txt
# - cd ansible
# - echo -e "[service-vms]\nlocalhost ansible_ssh_user=travis" > hosts
# - cat hosts
# - ansible-playbook playbooks/setup.yml --syntax-check
# - ansible-playbook -v playbooks/setup.yml -e "repository_url="$TRAVIS_BUILD_DIR -e  "repository_branch=HEAD"  --start-at-task="Upgrade packages." --connection=local -vvvv
# - cd /var/www/okeanos-LoD/webapp/
 - python manage.py makemigrations
 - python manage.py syncdb --noinput
 - python manage.py migrate
 - coverage run --source='.' --omit="*tests*","*webapp/webapp*","*webapp/backend/migrations*","*__init__*","*manage.py*" manage.py test
 - coverage report
 - cd ../

 # Central service
 - psql -c "DROP DATABASE lambda_db;" -U postgres
 - psql -c "CREATE DATABASE lambda_db;" -U postgres
 - export DJANGO_SETTINGS_MODULE=app.settings
 - cd central_service/app
 - python render_django_settings.py

 - pip install -r requirements.txt
 - python manage.py makemigrations
 - python manage.py syncdb --noinput
 - python manage.py migrate
 - coverage run --source='.' --omit="*tests*","*app/app*","*app/backend/migrations*","*__init__*","*manage.py*" manage.py test
 - coverage report
 - cd ../../

# Front end
 - cd webapp/frontend/
 - npm test

env:
#  - DJANGO_SETTINGS_MODULE="webapp.settings" TOXENV_CORE=py27
  - TOXENV_CORE=py27
