---
  - name: Install python-dev, sudo and git packages.
    apt: name={{ item }} state=latest
    with_items:
      - python-dev
      - sudo
      - git

  - name: Include apache2 tasks.
    include: apache-install.yml

  - name: Include postgresql-install tasks.
    include: postgresql-install.yml

  - name: Download Django code from Github.
    git: repo={{ repository_url }}  dest={{ repository_download_path }}/okeanos-LoD update=yes version={{ repository_branch }}

  - name: Change repository permissions.
    file: path={{ repository_download_path }} owner=celery group=celery recurse=yes

  - name: Install Fokia requirements.
    pip: requirements={{ repository_download_path }}/okeanos-LoD/core/requirements.txt

  - name: Install Webapp requirements.
    pip: requirements={{ repository_download_path }}/okeanos-LoD/webapp/requirements.txt

  - name: Install Fokia.
    command: python setup.py install chdir="{{ repository_download_path }}/okeanos-LoD/core/"

  - name: Create lambda_instances dir for ssh keys
    file: path=/home/celery/.ssh/lambda_instances state=directory mode=0755 owner=celery group=celery

  - name: Setup Django database configuration.
    template: src=settings.py.j2 dest={{ repository_download_path}}/okeanos-LoD/webapp/webapp/settings.py
    notify:
      - django_dbs_migrate

  - meta: flush_handlers

  - name: Create user fixture
    template: src=users.yaml.j2 dest={{ repository_download_path}}/okeanos-LoD/webapp/backend/fixtures/users.yaml

  - name: Load user from fixtures
    django_manage: command=loaddata app_path={{ repository_download_path }}/okeanos-LoD/webapp/ fixtures=users.yaml
